import type { DealershipDetails } from './monthlyReport';
import type { VehicleCondition } from './types';

export interface DealershipReportRow {
  id: string;
  customer_name: string;
  stock_number: string | null;
  salesperson_name: string | null;
  fsm_name: string | null;
  delivery_at: string;
  vehicle_condition: VehicleCondition | null;
}

const NAVY: [number, number, number] = [30, 58, 138];
const SLATE: [number, number, number] = [51, 65, 85];
const LIGHT_GRAY: [number, number, number] = [238, 241, 244];
const MID_GRAY: [number, number, number] = [204, 210, 217];
const MUTED: [number, number, number] = [107, 114, 128];
const DARK: [number, number, number] = [26, 26, 26];

// A Sales Manager's report is a read-only summary of what's delivered
// dealership-wide — unlike the salesperson's monthly report, it has no
// bonus content (that's personal payroll info) and no signature block
// (nothing here needs authorizing), so the layout is simpler and rarely
// needs the row-shrinking the bonus report does.
async function buildPdf(rows: DealershipReportRow[], dealershipName: string, monthLabel: string, generatedBy: string, dealership: DealershipDetails) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentW = pageW - margin * 2;

  // ---- header band ----
  const headerH = 92;
  doc.setFillColor(...LIGHT_GRAY);
  doc.rect(0, 0, pageW, headerH, 'F');
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...DARK);
  doc.text('AXIOM', margin, 36);
  const axiomW = doc.getTextWidth('AXIOM ');
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...NAVY);
  doc.text('Pulse', margin + axiomW, 36);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text('The Pulse of Every Delivery.', margin, 52);

  doc.setFontSize(9);
  doc.setTextColor(30, 64, 175);
  doc.text('by Rahul Champaneri', margin, 68);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...NAVY);
  doc.text('D E A L E R S H I P   D E L I V E R Y   R E P O R T', pageW - margin, 36, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(monthLabel.toUpperCase(), pageW - margin, 52, { align: 'right' });

  let y = headerH + 26;

  const newCount = rows.filter((r) => r.vehicle_condition === 'new').length;
  const usedCount = rows.filter((r) => r.vehicle_condition === 'used').length;

  // ---- stat tiles ----
  // New/Used counts take the DEALERSHIP tile's old spot — the dealership
  // name is already carried by the header title and footer, while New vs.
  // Used is the breakdown a Sales Manager is actually pulling this report
  // to track.
  const tileGap = 10;
  const tileW = (contentW - tileGap * 3) / 4;
  const tileH = 54;
  const tiles: [string, string][] = [
    ['MONTH', monthLabel],
    ['TOTAL DELIVERED', String(rows.length)],
    ['NEW', String(newCount)],
    ['USED', String(usedCount)],
  ];
  tiles.forEach(([label, value], i) => {
    const tx = margin + i * (tileW + tileGap);
    doc.setFillColor(255, 255, 255);
    doc.rect(tx, y, tileW, tileH, 'F');
    doc.setDrawColor(...MID_GRAY);
    doc.setLineWidth(0.8);
    doc.rect(tx, y, tileW, tileH, 'S');
    doc.setFillColor(...NAVY);
    doc.rect(tx, y, 2.5, tileH, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(label, tx + tileW / 2, y + 18, { align: 'center' });
    doc.setFontSize(value.length > 14 ? 11 : 15);
    doc.setTextColor(...NAVY);
    doc.text(value, tx + tileW / 2, y + 40, { align: 'center' });
  });

  y += tileH + 16;

  // ---- generated-by bar ----
  const barH = 24;
  doc.setFillColor(255, 255, 255);
  doc.rect(margin, y, contentW, barH, 'F');
  doc.setDrawColor(...MID_GRAY);
  doc.rect(margin, y, contentW, barH, 'S');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...DARK);
  doc.text(`${dealershipName.toUpperCase()} · GENERATED BY: ${generatedBy.toUpperCase()}`, margin + 10, y + 16);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  doc.text(`Generated ${new Date().toLocaleString()}`, pageW - margin - 10, y + 16, { align: 'right' });

  y += barH + 16;

  // ---- table ----
  const cols: { label: string; w: number }[] = [
    { label: 'Customer Name', w: contentW * 0.20 },
    { label: 'Stock #', w: contentW * 0.09 },
    { label: 'Condition', w: contentW * 0.10 },
    { label: 'Salesperson', w: contentW * 0.19 },
    { label: 'Finance Manager', w: contentW * 0.19 },
    { label: 'Date of Delivery', w: contentW * 0.23 },
  ];
  const headH = 22;

  const FOOTER_RESERVE = 48;
  const DEFAULT_ROW_H = 20;
  const MIN_ROW_H = 9;
  const DEFAULT_FONT = 9.5;
  const MIN_FONT = 6;
  const TOTAL_LINE_H = 32;
  const usableBottom = pageH - FOOTER_RESERVE;
  const availableForTable = usableBottom - y - headH - TOTAL_LINE_H;
  const idealRowH = rows.length > 0 ? availableForTable / rows.length : DEFAULT_ROW_H;
  const rowH = Math.min(DEFAULT_ROW_H, Math.max(MIN_ROW_H, idealRowH));
  const rowFont = Math.max(MIN_FONT, DEFAULT_FONT * (rowH / DEFAULT_ROW_H));
  const rowTextOffset = Math.max(rowH - 6, rowH * 0.65);

  doc.setFillColor(...SLATE);
  doc.rect(margin, y, contentW, headH, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  let cx = margin + 8;
  cols.forEach((col) => { doc.text(col.label.toUpperCase(), cx, y + 15); cx += col.w; });

  let ry = y + headH;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(rowFont);
  rows.forEach((r, i) => {
    if (i % 2 === 1) {
      doc.setFillColor(248, 249, 250);
      doc.rect(margin, ry, contentW, rowH, 'F');
    }
    doc.setTextColor(...DARK);
    let cellX = margin + 8;
    const values = [
      r.customer_name,
      r.stock_number || '—',
      r.vehicle_condition === 'new' ? 'New' : r.vehicle_condition === 'used' ? 'Used' : '—',
      r.salesperson_name || '—',
      r.fsm_name || '—',
      new Date(r.delivery_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }),
    ];
    values.forEach((v, idx) => { doc.text(v, cellX, ry + rowTextOffset); cellX += cols[idx].w; });
    ry += rowH;
  });
  doc.setDrawColor(...MID_GRAY);
  doc.setLineWidth(0.6);
  doc.line(margin, ry, margin + contentW, ry);

  y = ry + 20;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text(`TOTAL DELIVERED: ${rows.length}  ·  New: ${newCount}  ·  Used: ${usedCount}`, margin, y);

  // ---- footer ----
  const footerY = pageH - 34;
  doc.setDrawColor(...MID_GRAY);
  doc.setLineWidth(0.5);
  doc.line(margin, footerY - 10, pageW - margin, footerY - 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  const footerText = `${dealership.name} · ${dealership.address}, ${dealership.city} · ${dealership.phone} · Dealer Code ${dealership.dealerCode}`;
  doc.text(footerText, pageW / 2, footerY, { align: 'center' });
  doc.text(`Generated ${new Date().toLocaleString()}`, margin, footerY + 14);
  doc.text('Page 1', pageW - margin, footerY + 14, { align: 'right' });

  return doc;
}

function filenameFor(monthLabel: string): string {
  return `axiom-pulse-dealership-report-${monthLabel.replace(/\s+/g, '-').toLowerCase()}.pdf`;
}

export async function downloadDealershipReport(
  rows: DealershipReportRow[],
  dealershipName: string,
  monthLabel: string,
  generatedBy: string,
  dealership: DealershipDetails,
): Promise<void> {
  const doc = await buildPdf(rows, dealershipName, monthLabel, generatedBy, dealership);
  doc.save(filenameFor(monthLabel));
}

export async function shareDealershipReport(
  rows: DealershipReportRow[],
  dealershipName: string,
  monthLabel: string,
  generatedBy: string,
  dealership: DealershipDetails,
): Promise<'shared' | 'downloaded'> {
  const doc = await buildPdf(rows, dealershipName, monthLabel, generatedBy, dealership);
  const filename = filenameFor(monthLabel);
  const blob = doc.output('blob');
  const file = new File([blob], filename, { type: 'application/pdf' });

  const nav = navigator as Navigator & { canShare?: (data: { files: File[] }) => boolean };
  if (nav.share && nav.canShare?.({ files: [file] })) {
    try {
      await nav.share({ files: [file], title: 'Axiom Pulse — Dealership Delivery Report', text: `Deliveries — ${monthLabel}` });
      return 'shared';
    } catch {
      // User cancelled the share sheet, or it failed — fall through to download.
    }
  }
  doc.save(filename);
  return 'downloaded';
}
